### PR TITLE
[BUGFIX] Fix update of an entity's array relationship (#16)

### LINKED ISSUE #16: Update an entity's relationship with an array fails
When updating an entity's relationship OneToMany or ManyToMany (i.e. an array of objects) using the format described [in the documentation](https://github.com/trivago/jade/blob/master/docs/example.md) it fails because it can not find `relationships.<relationship_name>.data.id`, which is normal since `data` is an array.

### PR DESCRIPTION
**Pull request by regniblod**
Fixes #16.

### CODE REVIEW

File: Trivago/Jade/Application/JsonApi/Request/RequestFactory.php [hunk 1]
```diff
@@ -459,11 +456,12 @@ private function createRelationshipBag($data, $dataAsObject, $acceptNull)
             }
             $ids = [];
             foreach ($rawRelationship as $key => $singleRelationship) {
-               $this->validateRelationshipType(
-                   $singleRelationship,
-                   $relationshipName,
-                   sprintf('data.relationships.%s.data[%d].type', $relationshipName, $key)
-               );
+                $this->validateKeys('data.relationships.'.$relationshipName.'.data[]', $singleRelationship, ['id', 'type']);
```
Comment (moein) [inline Trivago/Jade/Application/JsonApi/Request/RequestFactory.php]: Please change data[] to data[$key] so the user knows in which key they have the issue

**Comment by regniblod** [comment]
PR updated with the fix.
